---
# Default scenario that does not require a FPGA to run.

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu_bionic
    image: ubuntu:bionic
    privileged: true
  - name: ubuntu_bionic_deps
    image: ubuntu:bionic
    privileged: true
  - name: centos_7
    image: centos:7
    privileged: true
  - name: centos_7_from_src
    image: centos:7
    privileged: true
  - name: centos_7_deps
    image: centos:7
    privileged: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      centos_7:
        accelize_drm_devel: true
      centos_7_from_src:
        accelize_drm_from_source: true
        accelize_drm_git_clone: /opt
      centos_7_deps:
        accelize_drm_no_install: true
        accelize_drm_test: true
        accelize_drm_build: true
        accelize_drm_build_doc: true
        accelize_drm_build_package: true
        accelize_drm_coverage: true
        accelize_drm_abi_check: true
      ubuntu_bionic:
        accelize_drm_devel: true
      ubuntu_bionic_deps:
        accelize_drm_no_install: true
        accelize_drm_test: true
        accelize_drm_build: true
        accelize_drm_build_doc: true
        accelize_drm_build_package: true
        accelize_drm_coverage: true
        accelize_drm_abi_check: true

verifier:
  name: testinfra

scenario:
  test_sequence:
    - create
    - converge
    - idempotence
    - verify
